### ISSUE TITLE
add readme to this repo ?

### ISSUE THREAD

**Issue by ppisljar** [milahu/opensubtitles-scraper-new-subs#1]
can you add the readme describing the shards and the current status ?
when do you think you can make per language dumps ?

**Comment by milahu** [comment]
## readme

nah, this is self-descriptive... its obvious what the shards are
but feel free to make a PR...

the shards are a way to store "a million small" files in git efficiently
by packing 1000 zip files into each shard. 1000 * 20KB = 20MB

this is similar to filesystems like [seaweedfs](https://github.com/seaweedfs/seaweedfs) - they call it "volumes"

> volume servers manage files and their metadata

> Each data volume is 32GB in size, and can hold a lot of files.

> Since each volume server only manages metadata of files on its own disk, with only 16 bytes for each file, all file access can read file metadata just from memory and only needs one disk operation to actually read file data. For comparison, consider that an xfs inode structure in Linux is 536 bytes.

before the shards, i stored each zip file in a separate git branch
but at 200K branches, `git push` and `git pull` became painfully slow

on design goal of this database is: avoid converting database files to save diskspace
so ideally, this should be an immutable append-only database
sqlite is fast and portable

## per language dumps

practically never.
its on my todo list, but has zero priority...

the problem with grouping by language is
that the language can be wrong in the metadata ([subtitles_all.txt.gz](https://dl.opensubtitles.org/addons/export/))
and the language can change in the future
this also affects [my last release](https://www.reddit.com/r/DataHoarder/comments/12yxcoy/opensubtitlesorg_dump_1_million_subtitles_23_gb/) (subs 9180519 to 9521948)

so the only constant is the subtitle number
and i will make future releases by ranges of subtitle numbers

when people want "grouped by language" releases... help yourself
running some python scripts is trivial
mostly `subtitles_all.txt.gz-parse.py` and `opensubs-db-split-by-lang.py`
you just have to navigate the mess in my [opensubtitles-scraper](https://github.com/milahu/opensubtitles-scraper) repo : P

problem with [the first release](https://www.reddit.com/r/DataHoarder/comments/w7sgcz/5719123_subtitles_from_opensubtitlesorg/) (subs 1 to 9180517) is: some subs are missing
when using subtitles_all.txt.gz as the reference (expected value)
so im planning to make a "diff release" for that, to add missing files
a complete re-release would be a waste of diskspace (130GB)

i will be forced to make a new release on archive.org / torrent
when this repo grows larger than 5GB (soft limit) or 10GB (hard limit)
currently its about 4GB...

## problem of trust

one fundamental problem with this project is:
you have to trust me that i dont modify the data

the subtitle files have only MD5 checksums in the *.nfo files
but there are no cryptographic signatures
so i cannot prove that these are the original files

best i can do is being transparent about this problem

i could offer a money-reward if you find bad files
but nah, this just creates an illusion of integrity
because realistically, no one will download all 7M files to check them

there are SSL notary services like [tlsnotary](https://github.com/tlsnotary/tlsn) but this also just moves the problem
and the actual problem is that the original data has no signatures

a P2P web-scraping network would be nice...

**Comment by milahu** [comment]
> describing the shards

actually, these 20 MB shards are only needed for git and github
for files, github has a soft limit of 50 MB, and a hard limit of 100 MB
there is git-lfs, but... nah

so i will keep using the shards for this repo (release early, release often)
so people can fetch the latest subs, without waiting for the next release

but for distribution and long-term storage, the shards are not helpful
so in future releases, i will pack 100 shards into one sqlite database
each release has 100_000 subtitles = 2 GB

**Comment by milahu** [comment]
mkay...
i just refactored this repo from subdirs to git branches
this makes `git clone` and `git pull` a bit more complex
so now i added a readme
